packages:
  - "apps/*"
  - "packages/*"

catalogs:
  build:
    "@types/node": "^24.6.2"
    "typescript": "^5.9.3"
  react:
    "react": "^19.2.0"
    "react-dom": "^19.2.0"
    "next": "^16.0.0"
    "@types/react": "^19.1.9"
    "@types/react-dom": "^19.1.7"
    "babel-plugin-react-compiler": "^1.0.0"
    "eslint-config-next": "16.0.0"