packages:
  - "apps/*"
  - "packages/*"
# TODO: re-enable in the future
# currently disabled because react had RCE vulnerability and patch was released yesterday
# minimumReleaseAge: 10080
# minimumReleaseAgeExclude:
#   - transletta
catalogs:
  build:
    "@types/node": "^24.6.2"
    "typescript": "^5.9.3"
    "@typescript/native-preview": "^7.0.0-dev.20260109.1"
  tailwind:
    "@tailwindcss/postcss": "^4"
    "tailwindcss": "^4"
  react:
    "react": "^19.2.1"
    "react-dom": "^19.2.1"
    "next": "^16.1.1"
    "@vercel/analytics": "^1.6.1"
    "@types/react": "^19.2.7"
    "@types/react-dom": "^19.2.3"
    "babel-plugin-react-compiler": "^1.0.0"
    "eslint-config-next": "16.0.7"