packages:
  - "apps/*"
  - "packages/*"
# minimumReleaseAge: 10080
# minimumReleaseAgeExclude:
#   - transletta
catalogs:
  build:
    "@types/node": "^24.6.2"
    "typescript": "^5.9.3"
  react:
    "react": "^19.2.1"
    "react-dom": "^19.2.1"
    "next": "^16.0.7"
    "@types/react": "^19.2.7"
    "@types/react-dom": "^19.2.3"
    "babel-plugin-react-compiler": "^1.0.0"
    "eslint-config-next": "16.0.7"