packages:
  - apps/*
  - packages/*

catalogs:
  build:
    '@types/node': ^24.6.2
    typescript: ^5.9.3
  react:
    react: ^19.1.0
    react-dom: ^19.1.0
    next: ^15.6.0-canary.42
    '@types/react': ^19.1.9
    '@types/react-dom': ^19.1.7
    babel-plugin-react-compiler: 19.1.0-rc.3
    eslint-config-next: 15.6.0-canary.42

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - core-js-pure
  - sharp
  - unrs-resolver
