import { join } from 'node:path';

const HEADER =
  '// THIS FILE IS AUTO-GENERATED BY THE "generate-schema" COMMAND\n// DO NOT EDIT THIS FILE DIRECTLY\n';
const DRIZZLE_DIR = join(import.meta.dirname!, '../drizzle');
const SCHEMA_DIR = join(import.meta.dirname!, '../src/database/schema');
const RELATIONS_DIR = join(SCHEMA_DIR, 'relations');
const TABLES_DIR = join(SCHEMA_DIR, 'tables');
const OUTPUT_DIR = join(SCHEMA_DIR, '../schema.ts');

let output = `${HEADER}\n`;

// export all tables
output += '/* Tables */\n';
for await (const file of Deno.readDir(TABLES_DIR)) {
  output += `export * from './schema/tables/${file.name}';\n`;
}

// export all relations
output += '\n/* Relations */\n';
for await (const file of Deno.readDir(RELATIONS_DIR)) {
  output += `export * from './schema/relations/${file.name}';\n`;
}

await Deno.writeTextFile(OUTPUT_DIR, output);

// ensure drizzle directory exists
await Deno.mkdir(DRIZZLE_DIR, { recursive: true }).catch(Object);

console.log(`Schema generated successfully in ${OUTPUT_DIR}`);
