
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `RestEntity` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model RestEntity
 * 
 */
export type RestEntityModel = runtime.Types.Result.DefaultSelection<Prisma.$RestEntityPayload>

export type AggregateRestEntity = {
  _count: RestEntityCountAggregateOutputType | null
  _min: RestEntityMinAggregateOutputType | null
  _max: RestEntityMaxAggregateOutputType | null
}

export type RestEntityMinAggregateOutputType = {
  id: string | null
  name: string | null
  createdAt: Date | null
  updatedAt: Date | null
  workspaceId: string | null
}

export type RestEntityMaxAggregateOutputType = {
  id: string | null
  name: string | null
  createdAt: Date | null
  updatedAt: Date | null
  workspaceId: string | null
}

export type RestEntityCountAggregateOutputType = {
  id: number
  name: number
  metadata: number
  createdAt: number
  updatedAt: number
  workspaceId: number
  _all: number
}


export type RestEntityMinAggregateInputType = {
  id?: true
  name?: true
  createdAt?: true
  updatedAt?: true
  workspaceId?: true
}

export type RestEntityMaxAggregateInputType = {
  id?: true
  name?: true
  createdAt?: true
  updatedAt?: true
  workspaceId?: true
}

export type RestEntityCountAggregateInputType = {
  id?: true
  name?: true
  metadata?: true
  createdAt?: true
  updatedAt?: true
  workspaceId?: true
  _all?: true
}

export type RestEntityAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RestEntity to aggregate.
   */
  where?: Prisma.RestEntityWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RestEntities to fetch.
   */
  orderBy?: Prisma.RestEntityOrderByWithRelationInput | Prisma.RestEntityOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RestEntityWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RestEntities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RestEntities.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned RestEntities
  **/
  _count?: true | RestEntityCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RestEntityMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RestEntityMaxAggregateInputType
}

export type GetRestEntityAggregateType<T extends RestEntityAggregateArgs> = {
      [P in keyof T & keyof AggregateRestEntity]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRestEntity[P]>
    : Prisma.GetScalarType<T[P], AggregateRestEntity[P]>
}




export type RestEntityGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RestEntityWhereInput
  orderBy?: Prisma.RestEntityOrderByWithAggregationInput | Prisma.RestEntityOrderByWithAggregationInput[]
  by: Prisma.RestEntityScalarFieldEnum[] | Prisma.RestEntityScalarFieldEnum
  having?: Prisma.RestEntityScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RestEntityCountAggregateInputType | true
  _min?: RestEntityMinAggregateInputType
  _max?: RestEntityMaxAggregateInputType
}

export type RestEntityGroupByOutputType = {
  id: string
  name: string
  metadata: runtime.JsonValue
  createdAt: Date
  updatedAt: Date
  workspaceId: string
  _count: RestEntityCountAggregateOutputType | null
  _min: RestEntityMinAggregateOutputType | null
  _max: RestEntityMaxAggregateOutputType | null
}

type GetRestEntityGroupByPayload<T extends RestEntityGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RestEntityGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RestEntityGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RestEntityGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RestEntityGroupByOutputType[P]>
      }
    >
  >



export type RestEntityWhereInput = {
  AND?: Prisma.RestEntityWhereInput | Prisma.RestEntityWhereInput[]
  OR?: Prisma.RestEntityWhereInput[]
  NOT?: Prisma.RestEntityWhereInput | Prisma.RestEntityWhereInput[]
  id?: Prisma.StringFilter<"RestEntity"> | string
  name?: Prisma.StringFilter<"RestEntity"> | string
  metadata?: Prisma.JsonFilter<"RestEntity">
  createdAt?: Prisma.DateTimeFilter<"RestEntity"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"RestEntity"> | Date | string
  workspaceId?: Prisma.StringFilter<"RestEntity"> | string
  workspace?: Prisma.XOR<Prisma.WorkspaceScalarRelationFilter, Prisma.WorkspaceWhereInput>
}

export type RestEntityOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  metadata?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  workspaceId?: Prisma.SortOrder
  workspace?: Prisma.WorkspaceOrderByWithRelationInput
}

export type RestEntityWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.RestEntityWhereInput | Prisma.RestEntityWhereInput[]
  OR?: Prisma.RestEntityWhereInput[]
  NOT?: Prisma.RestEntityWhereInput | Prisma.RestEntityWhereInput[]
  name?: Prisma.StringFilter<"RestEntity"> | string
  metadata?: Prisma.JsonFilter<"RestEntity">
  createdAt?: Prisma.DateTimeFilter<"RestEntity"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"RestEntity"> | Date | string
  workspaceId?: Prisma.StringFilter<"RestEntity"> | string
  workspace?: Prisma.XOR<Prisma.WorkspaceScalarRelationFilter, Prisma.WorkspaceWhereInput>
}, "id">

export type RestEntityOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  metadata?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  workspaceId?: Prisma.SortOrder
  _count?: Prisma.RestEntityCountOrderByAggregateInput
  _max?: Prisma.RestEntityMaxOrderByAggregateInput
  _min?: Prisma.RestEntityMinOrderByAggregateInput
}

export type RestEntityScalarWhereWithAggregatesInput = {
  AND?: Prisma.RestEntityScalarWhereWithAggregatesInput | Prisma.RestEntityScalarWhereWithAggregatesInput[]
  OR?: Prisma.RestEntityScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RestEntityScalarWhereWithAggregatesInput | Prisma.RestEntityScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"RestEntity"> | string
  name?: Prisma.StringWithAggregatesFilter<"RestEntity"> | string
  metadata?: Prisma.JsonWithAggregatesFilter<"RestEntity">
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"RestEntity"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"RestEntity"> | Date | string
  workspaceId?: Prisma.StringWithAggregatesFilter<"RestEntity"> | string
}

export type RestEntityCreateInput = {
  id?: string
  name: string
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  workspace: Prisma.WorkspaceCreateNestedOneWithoutRestEntityInput
}

export type RestEntityUncheckedCreateInput = {
  id?: string
  name: string
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  workspaceId: string
}

export type RestEntityUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workspace?: Prisma.WorkspaceUpdateOneRequiredWithoutRestEntityNestedInput
}

export type RestEntityUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workspaceId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type RestEntityCreateManyInput = {
  id?: string
  name: string
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  workspaceId: string
}

export type RestEntityUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RestEntityUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workspaceId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type RestEntityListRelationFilter = {
  every?: Prisma.RestEntityWhereInput
  some?: Prisma.RestEntityWhereInput
  none?: Prisma.RestEntityWhereInput
}

export type RestEntityOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type RestEntityCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  metadata?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  workspaceId?: Prisma.SortOrder
}

export type RestEntityMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  workspaceId?: Prisma.SortOrder
}

export type RestEntityMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  workspaceId?: Prisma.SortOrder
}

export type RestEntityCreateNestedManyWithoutWorkspaceInput = {
  create?: Prisma.XOR<Prisma.RestEntityCreateWithoutWorkspaceInput, Prisma.RestEntityUncheckedCreateWithoutWorkspaceInput> | Prisma.RestEntityCreateWithoutWorkspaceInput[] | Prisma.RestEntityUncheckedCreateWithoutWorkspaceInput[]
  connectOrCreate?: Prisma.RestEntityCreateOrConnectWithoutWorkspaceInput | Prisma.RestEntityCreateOrConnectWithoutWorkspaceInput[]
  createMany?: Prisma.RestEntityCreateManyWorkspaceInputEnvelope
  connect?: Prisma.RestEntityWhereUniqueInput | Prisma.RestEntityWhereUniqueInput[]
}

export type RestEntityUncheckedCreateNestedManyWithoutWorkspaceInput = {
  create?: Prisma.XOR<Prisma.RestEntityCreateWithoutWorkspaceInput, Prisma.RestEntityUncheckedCreateWithoutWorkspaceInput> | Prisma.RestEntityCreateWithoutWorkspaceInput[] | Prisma.RestEntityUncheckedCreateWithoutWorkspaceInput[]
  connectOrCreate?: Prisma.RestEntityCreateOrConnectWithoutWorkspaceInput | Prisma.RestEntityCreateOrConnectWithoutWorkspaceInput[]
  createMany?: Prisma.RestEntityCreateManyWorkspaceInputEnvelope
  connect?: Prisma.RestEntityWhereUniqueInput | Prisma.RestEntityWhereUniqueInput[]
}

export type RestEntityUpdateManyWithoutWorkspaceNestedInput = {
  create?: Prisma.XOR<Prisma.RestEntityCreateWithoutWorkspaceInput, Prisma.RestEntityUncheckedCreateWithoutWorkspaceInput> | Prisma.RestEntityCreateWithoutWorkspaceInput[] | Prisma.RestEntityUncheckedCreateWithoutWorkspaceInput[]
  connectOrCreate?: Prisma.RestEntityCreateOrConnectWithoutWorkspaceInput | Prisma.RestEntityCreateOrConnectWithoutWorkspaceInput[]
  upsert?: Prisma.RestEntityUpsertWithWhereUniqueWithoutWorkspaceInput | Prisma.RestEntityUpsertWithWhereUniqueWithoutWorkspaceInput[]
  createMany?: Prisma.RestEntityCreateManyWorkspaceInputEnvelope
  set?: Prisma.RestEntityWhereUniqueInput | Prisma.RestEntityWhereUniqueInput[]
  disconnect?: Prisma.RestEntityWhereUniqueInput | Prisma.RestEntityWhereUniqueInput[]
  delete?: Prisma.RestEntityWhereUniqueInput | Prisma.RestEntityWhereUniqueInput[]
  connect?: Prisma.RestEntityWhereUniqueInput | Prisma.RestEntityWhereUniqueInput[]
  update?: Prisma.RestEntityUpdateWithWhereUniqueWithoutWorkspaceInput | Prisma.RestEntityUpdateWithWhereUniqueWithoutWorkspaceInput[]
  updateMany?: Prisma.RestEntityUpdateManyWithWhereWithoutWorkspaceInput | Prisma.RestEntityUpdateManyWithWhereWithoutWorkspaceInput[]
  deleteMany?: Prisma.RestEntityScalarWhereInput | Prisma.RestEntityScalarWhereInput[]
}

export type RestEntityUncheckedUpdateManyWithoutWorkspaceNestedInput = {
  create?: Prisma.XOR<Prisma.RestEntityCreateWithoutWorkspaceInput, Prisma.RestEntityUncheckedCreateWithoutWorkspaceInput> | Prisma.RestEntityCreateWithoutWorkspaceInput[] | Prisma.RestEntityUncheckedCreateWithoutWorkspaceInput[]
  connectOrCreate?: Prisma.RestEntityCreateOrConnectWithoutWorkspaceInput | Prisma.RestEntityCreateOrConnectWithoutWorkspaceInput[]
  upsert?: Prisma.RestEntityUpsertWithWhereUniqueWithoutWorkspaceInput | Prisma.RestEntityUpsertWithWhereUniqueWithoutWorkspaceInput[]
  createMany?: Prisma.RestEntityCreateManyWorkspaceInputEnvelope
  set?: Prisma.RestEntityWhereUniqueInput | Prisma.RestEntityWhereUniqueInput[]
  disconnect?: Prisma.RestEntityWhereUniqueInput | Prisma.RestEntityWhereUniqueInput[]
  delete?: Prisma.RestEntityWhereUniqueInput | Prisma.RestEntityWhereUniqueInput[]
  connect?: Prisma.RestEntityWhereUniqueInput | Prisma.RestEntityWhereUniqueInput[]
  update?: Prisma.RestEntityUpdateWithWhereUniqueWithoutWorkspaceInput | Prisma.RestEntityUpdateWithWhereUniqueWithoutWorkspaceInput[]
  updateMany?: Prisma.RestEntityUpdateManyWithWhereWithoutWorkspaceInput | Prisma.RestEntityUpdateManyWithWhereWithoutWorkspaceInput[]
  deleteMany?: Prisma.RestEntityScalarWhereInput | Prisma.RestEntityScalarWhereInput[]
}

export type RestEntityCreateWithoutWorkspaceInput = {
  id?: string
  name: string
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RestEntityUncheckedCreateWithoutWorkspaceInput = {
  id?: string
  name: string
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RestEntityCreateOrConnectWithoutWorkspaceInput = {
  where: Prisma.RestEntityWhereUniqueInput
  create: Prisma.XOR<Prisma.RestEntityCreateWithoutWorkspaceInput, Prisma.RestEntityUncheckedCreateWithoutWorkspaceInput>
}

export type RestEntityCreateManyWorkspaceInputEnvelope = {
  data: Prisma.RestEntityCreateManyWorkspaceInput | Prisma.RestEntityCreateManyWorkspaceInput[]
}

export type RestEntityUpsertWithWhereUniqueWithoutWorkspaceInput = {
  where: Prisma.RestEntityWhereUniqueInput
  update: Prisma.XOR<Prisma.RestEntityUpdateWithoutWorkspaceInput, Prisma.RestEntityUncheckedUpdateWithoutWorkspaceInput>
  create: Prisma.XOR<Prisma.RestEntityCreateWithoutWorkspaceInput, Prisma.RestEntityUncheckedCreateWithoutWorkspaceInput>
}

export type RestEntityUpdateWithWhereUniqueWithoutWorkspaceInput = {
  where: Prisma.RestEntityWhereUniqueInput
  data: Prisma.XOR<Prisma.RestEntityUpdateWithoutWorkspaceInput, Prisma.RestEntityUncheckedUpdateWithoutWorkspaceInput>
}

export type RestEntityUpdateManyWithWhereWithoutWorkspaceInput = {
  where: Prisma.RestEntityScalarWhereInput
  data: Prisma.XOR<Prisma.RestEntityUpdateManyMutationInput, Prisma.RestEntityUncheckedUpdateManyWithoutWorkspaceInput>
}

export type RestEntityScalarWhereInput = {
  AND?: Prisma.RestEntityScalarWhereInput | Prisma.RestEntityScalarWhereInput[]
  OR?: Prisma.RestEntityScalarWhereInput[]
  NOT?: Prisma.RestEntityScalarWhereInput | Prisma.RestEntityScalarWhereInput[]
  id?: Prisma.StringFilter<"RestEntity"> | string
  name?: Prisma.StringFilter<"RestEntity"> | string
  metadata?: Prisma.JsonFilter<"RestEntity">
  createdAt?: Prisma.DateTimeFilter<"RestEntity"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"RestEntity"> | Date | string
  workspaceId?: Prisma.StringFilter<"RestEntity"> | string
}

export type RestEntityCreateManyWorkspaceInput = {
  id?: string
  name: string
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RestEntityUpdateWithoutWorkspaceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RestEntityUncheckedUpdateWithoutWorkspaceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RestEntityUncheckedUpdateManyWithoutWorkspaceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type RestEntitySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  metadata?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  workspaceId?: boolean
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
}, ExtArgs["result"]["restEntity"]>

export type RestEntitySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  metadata?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  workspaceId?: boolean
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
}, ExtArgs["result"]["restEntity"]>

export type RestEntitySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  metadata?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  workspaceId?: boolean
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
}, ExtArgs["result"]["restEntity"]>

export type RestEntitySelectScalar = {
  id?: boolean
  name?: boolean
  metadata?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  workspaceId?: boolean
}

export type RestEntityOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "metadata" | "createdAt" | "updatedAt" | "workspaceId", ExtArgs["result"]["restEntity"]>
export type RestEntityInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
}
export type RestEntityIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
}
export type RestEntityIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
}

export type $RestEntityPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "RestEntity"
  objects: {
    workspace: Prisma.$WorkspacePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    metadata: runtime.JsonValue
    createdAt: Date
    updatedAt: Date
    workspaceId: string
  }, ExtArgs["result"]["restEntity"]>
  composites: {}
}

export type RestEntityGetPayload<S extends boolean | null | undefined | RestEntityDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RestEntityPayload, S>

export type RestEntityCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RestEntityFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RestEntityCountAggregateInputType | true
  }

export interface RestEntityDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['RestEntity'], meta: { name: 'RestEntity' } }
  /**
   * Find zero or one RestEntity that matches the filter.
   * @param {RestEntityFindUniqueArgs} args - Arguments to find a RestEntity
   * @example
   * // Get one RestEntity
   * const restEntity = await prisma.restEntity.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RestEntityFindUniqueArgs>(args: Prisma.SelectSubset<T, RestEntityFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RestEntityClient<runtime.Types.Result.GetResult<Prisma.$RestEntityPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one RestEntity that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RestEntityFindUniqueOrThrowArgs} args - Arguments to find a RestEntity
   * @example
   * // Get one RestEntity
   * const restEntity = await prisma.restEntity.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RestEntityFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RestEntityFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RestEntityClient<runtime.Types.Result.GetResult<Prisma.$RestEntityPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RestEntity that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RestEntityFindFirstArgs} args - Arguments to find a RestEntity
   * @example
   * // Get one RestEntity
   * const restEntity = await prisma.restEntity.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RestEntityFindFirstArgs>(args?: Prisma.SelectSubset<T, RestEntityFindFirstArgs<ExtArgs>>): Prisma.Prisma__RestEntityClient<runtime.Types.Result.GetResult<Prisma.$RestEntityPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RestEntity that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RestEntityFindFirstOrThrowArgs} args - Arguments to find a RestEntity
   * @example
   * // Get one RestEntity
   * const restEntity = await prisma.restEntity.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RestEntityFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RestEntityFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RestEntityClient<runtime.Types.Result.GetResult<Prisma.$RestEntityPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more RestEntities that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RestEntityFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all RestEntities
   * const restEntities = await prisma.restEntity.findMany()
   * 
   * // Get first 10 RestEntities
   * const restEntities = await prisma.restEntity.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const restEntityWithIdOnly = await prisma.restEntity.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends RestEntityFindManyArgs>(args?: Prisma.SelectSubset<T, RestEntityFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RestEntityPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a RestEntity.
   * @param {RestEntityCreateArgs} args - Arguments to create a RestEntity.
   * @example
   * // Create one RestEntity
   * const RestEntity = await prisma.restEntity.create({
   *   data: {
   *     // ... data to create a RestEntity
   *   }
   * })
   * 
   */
  create<T extends RestEntityCreateArgs>(args: Prisma.SelectSubset<T, RestEntityCreateArgs<ExtArgs>>): Prisma.Prisma__RestEntityClient<runtime.Types.Result.GetResult<Prisma.$RestEntityPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many RestEntities.
   * @param {RestEntityCreateManyArgs} args - Arguments to create many RestEntities.
   * @example
   * // Create many RestEntities
   * const restEntity = await prisma.restEntity.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RestEntityCreateManyArgs>(args?: Prisma.SelectSubset<T, RestEntityCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many RestEntities and returns the data saved in the database.
   * @param {RestEntityCreateManyAndReturnArgs} args - Arguments to create many RestEntities.
   * @example
   * // Create many RestEntities
   * const restEntity = await prisma.restEntity.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many RestEntities and only return the `id`
   * const restEntityWithIdOnly = await prisma.restEntity.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends RestEntityCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, RestEntityCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RestEntityPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a RestEntity.
   * @param {RestEntityDeleteArgs} args - Arguments to delete one RestEntity.
   * @example
   * // Delete one RestEntity
   * const RestEntity = await prisma.restEntity.delete({
   *   where: {
   *     // ... filter to delete one RestEntity
   *   }
   * })
   * 
   */
  delete<T extends RestEntityDeleteArgs>(args: Prisma.SelectSubset<T, RestEntityDeleteArgs<ExtArgs>>): Prisma.Prisma__RestEntityClient<runtime.Types.Result.GetResult<Prisma.$RestEntityPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one RestEntity.
   * @param {RestEntityUpdateArgs} args - Arguments to update one RestEntity.
   * @example
   * // Update one RestEntity
   * const restEntity = await prisma.restEntity.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RestEntityUpdateArgs>(args: Prisma.SelectSubset<T, RestEntityUpdateArgs<ExtArgs>>): Prisma.Prisma__RestEntityClient<runtime.Types.Result.GetResult<Prisma.$RestEntityPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more RestEntities.
   * @param {RestEntityDeleteManyArgs} args - Arguments to filter RestEntities to delete.
   * @example
   * // Delete a few RestEntities
   * const { count } = await prisma.restEntity.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RestEntityDeleteManyArgs>(args?: Prisma.SelectSubset<T, RestEntityDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RestEntities.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RestEntityUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many RestEntities
   * const restEntity = await prisma.restEntity.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RestEntityUpdateManyArgs>(args: Prisma.SelectSubset<T, RestEntityUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RestEntities and returns the data updated in the database.
   * @param {RestEntityUpdateManyAndReturnArgs} args - Arguments to update many RestEntities.
   * @example
   * // Update many RestEntities
   * const restEntity = await prisma.restEntity.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more RestEntities and only return the `id`
   * const restEntityWithIdOnly = await prisma.restEntity.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends RestEntityUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, RestEntityUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RestEntityPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one RestEntity.
   * @param {RestEntityUpsertArgs} args - Arguments to update or create a RestEntity.
   * @example
   * // Update or create a RestEntity
   * const restEntity = await prisma.restEntity.upsert({
   *   create: {
   *     // ... data to create a RestEntity
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the RestEntity we want to update
   *   }
   * })
   */
  upsert<T extends RestEntityUpsertArgs>(args: Prisma.SelectSubset<T, RestEntityUpsertArgs<ExtArgs>>): Prisma.Prisma__RestEntityClient<runtime.Types.Result.GetResult<Prisma.$RestEntityPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of RestEntities.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RestEntityCountArgs} args - Arguments to filter RestEntities to count.
   * @example
   * // Count the number of RestEntities
   * const count = await prisma.restEntity.count({
   *   where: {
   *     // ... the filter for the RestEntities we want to count
   *   }
   * })
  **/
  count<T extends RestEntityCountArgs>(
    args?: Prisma.Subset<T, RestEntityCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RestEntityCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a RestEntity.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RestEntityAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RestEntityAggregateArgs>(args: Prisma.Subset<T, RestEntityAggregateArgs>): Prisma.PrismaPromise<GetRestEntityAggregateType<T>>

  /**
   * Group by RestEntity.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RestEntityGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RestEntityGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RestEntityGroupByArgs['orderBy'] }
      : { orderBy?: RestEntityGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RestEntityGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRestEntityGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the RestEntity model
 */
readonly fields: RestEntityFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for RestEntity.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RestEntityClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  workspace<T extends Prisma.WorkspaceDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.WorkspaceDefaultArgs<ExtArgs>>): Prisma.Prisma__WorkspaceClient<runtime.Types.Result.GetResult<Prisma.$WorkspacePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the RestEntity model
 */
export interface RestEntityFieldRefs {
  readonly id: Prisma.FieldRef<"RestEntity", 'String'>
  readonly name: Prisma.FieldRef<"RestEntity", 'String'>
  readonly metadata: Prisma.FieldRef<"RestEntity", 'Json'>
  readonly createdAt: Prisma.FieldRef<"RestEntity", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"RestEntity", 'DateTime'>
  readonly workspaceId: Prisma.FieldRef<"RestEntity", 'String'>
}
    

// Custom InputTypes
/**
 * RestEntity findUnique
 */
export type RestEntityFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RestEntity
   */
  select?: Prisma.RestEntitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the RestEntity
   */
  omit?: Prisma.RestEntityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RestEntityInclude<ExtArgs> | null
  /**
   * Filter, which RestEntity to fetch.
   */
  where: Prisma.RestEntityWhereUniqueInput
}

/**
 * RestEntity findUniqueOrThrow
 */
export type RestEntityFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RestEntity
   */
  select?: Prisma.RestEntitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the RestEntity
   */
  omit?: Prisma.RestEntityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RestEntityInclude<ExtArgs> | null
  /**
   * Filter, which RestEntity to fetch.
   */
  where: Prisma.RestEntityWhereUniqueInput
}

/**
 * RestEntity findFirst
 */
export type RestEntityFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RestEntity
   */
  select?: Prisma.RestEntitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the RestEntity
   */
  omit?: Prisma.RestEntityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RestEntityInclude<ExtArgs> | null
  /**
   * Filter, which RestEntity to fetch.
   */
  where?: Prisma.RestEntityWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RestEntities to fetch.
   */
  orderBy?: Prisma.RestEntityOrderByWithRelationInput | Prisma.RestEntityOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RestEntities.
   */
  cursor?: Prisma.RestEntityWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RestEntities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RestEntities.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RestEntities.
   */
  distinct?: Prisma.RestEntityScalarFieldEnum | Prisma.RestEntityScalarFieldEnum[]
}

/**
 * RestEntity findFirstOrThrow
 */
export type RestEntityFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RestEntity
   */
  select?: Prisma.RestEntitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the RestEntity
   */
  omit?: Prisma.RestEntityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RestEntityInclude<ExtArgs> | null
  /**
   * Filter, which RestEntity to fetch.
   */
  where?: Prisma.RestEntityWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RestEntities to fetch.
   */
  orderBy?: Prisma.RestEntityOrderByWithRelationInput | Prisma.RestEntityOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RestEntities.
   */
  cursor?: Prisma.RestEntityWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RestEntities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RestEntities.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RestEntities.
   */
  distinct?: Prisma.RestEntityScalarFieldEnum | Prisma.RestEntityScalarFieldEnum[]
}

/**
 * RestEntity findMany
 */
export type RestEntityFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RestEntity
   */
  select?: Prisma.RestEntitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the RestEntity
   */
  omit?: Prisma.RestEntityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RestEntityInclude<ExtArgs> | null
  /**
   * Filter, which RestEntities to fetch.
   */
  where?: Prisma.RestEntityWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RestEntities to fetch.
   */
  orderBy?: Prisma.RestEntityOrderByWithRelationInput | Prisma.RestEntityOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing RestEntities.
   */
  cursor?: Prisma.RestEntityWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RestEntities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RestEntities.
   */
  skip?: number
  distinct?: Prisma.RestEntityScalarFieldEnum | Prisma.RestEntityScalarFieldEnum[]
}

/**
 * RestEntity create
 */
export type RestEntityCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RestEntity
   */
  select?: Prisma.RestEntitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the RestEntity
   */
  omit?: Prisma.RestEntityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RestEntityInclude<ExtArgs> | null
  /**
   * The data needed to create a RestEntity.
   */
  data: Prisma.XOR<Prisma.RestEntityCreateInput, Prisma.RestEntityUncheckedCreateInput>
}

/**
 * RestEntity createMany
 */
export type RestEntityCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many RestEntities.
   */
  data: Prisma.RestEntityCreateManyInput | Prisma.RestEntityCreateManyInput[]
}

/**
 * RestEntity createManyAndReturn
 */
export type RestEntityCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RestEntity
   */
  select?: Prisma.RestEntitySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RestEntity
   */
  omit?: Prisma.RestEntityOmit<ExtArgs> | null
  /**
   * The data used to create many RestEntities.
   */
  data: Prisma.RestEntityCreateManyInput | Prisma.RestEntityCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RestEntityIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * RestEntity update
 */
export type RestEntityUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RestEntity
   */
  select?: Prisma.RestEntitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the RestEntity
   */
  omit?: Prisma.RestEntityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RestEntityInclude<ExtArgs> | null
  /**
   * The data needed to update a RestEntity.
   */
  data: Prisma.XOR<Prisma.RestEntityUpdateInput, Prisma.RestEntityUncheckedUpdateInput>
  /**
   * Choose, which RestEntity to update.
   */
  where: Prisma.RestEntityWhereUniqueInput
}

/**
 * RestEntity updateMany
 */
export type RestEntityUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update RestEntities.
   */
  data: Prisma.XOR<Prisma.RestEntityUpdateManyMutationInput, Prisma.RestEntityUncheckedUpdateManyInput>
  /**
   * Filter which RestEntities to update
   */
  where?: Prisma.RestEntityWhereInput
  /**
   * Limit how many RestEntities to update.
   */
  limit?: number
}

/**
 * RestEntity updateManyAndReturn
 */
export type RestEntityUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RestEntity
   */
  select?: Prisma.RestEntitySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RestEntity
   */
  omit?: Prisma.RestEntityOmit<ExtArgs> | null
  /**
   * The data used to update RestEntities.
   */
  data: Prisma.XOR<Prisma.RestEntityUpdateManyMutationInput, Prisma.RestEntityUncheckedUpdateManyInput>
  /**
   * Filter which RestEntities to update
   */
  where?: Prisma.RestEntityWhereInput
  /**
   * Limit how many RestEntities to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RestEntityIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * RestEntity upsert
 */
export type RestEntityUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RestEntity
   */
  select?: Prisma.RestEntitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the RestEntity
   */
  omit?: Prisma.RestEntityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RestEntityInclude<ExtArgs> | null
  /**
   * The filter to search for the RestEntity to update in case it exists.
   */
  where: Prisma.RestEntityWhereUniqueInput
  /**
   * In case the RestEntity found by the `where` argument doesn't exist, create a new RestEntity with this data.
   */
  create: Prisma.XOR<Prisma.RestEntityCreateInput, Prisma.RestEntityUncheckedCreateInput>
  /**
   * In case the RestEntity was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RestEntityUpdateInput, Prisma.RestEntityUncheckedUpdateInput>
}

/**
 * RestEntity delete
 */
export type RestEntityDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RestEntity
   */
  select?: Prisma.RestEntitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the RestEntity
   */
  omit?: Prisma.RestEntityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RestEntityInclude<ExtArgs> | null
  /**
   * Filter which RestEntity to delete.
   */
  where: Prisma.RestEntityWhereUniqueInput
}

/**
 * RestEntity deleteMany
 */
export type RestEntityDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RestEntities to delete
   */
  where?: Prisma.RestEntityWhereInput
  /**
   * Limit how many RestEntities to delete.
   */
  limit?: number
}

/**
 * RestEntity without action
 */
export type RestEntityDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RestEntity
   */
  select?: Prisma.RestEntitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the RestEntity
   */
  omit?: Prisma.RestEntityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RestEntityInclude<ExtArgs> | null
}
