
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `WorkspaceConfiguration` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model WorkspaceConfiguration
 * 
 */
export type WorkspaceConfigurationModel = runtime.Types.Result.DefaultSelection<Prisma.$WorkspaceConfigurationPayload>

export type AggregateWorkspaceConfiguration = {
  _count: WorkspaceConfigurationCountAggregateOutputType | null
  _avg: WorkspaceConfigurationAvgAggregateOutputType | null
  _sum: WorkspaceConfigurationSumAggregateOutputType | null
  _min: WorkspaceConfigurationMinAggregateOutputType | null
  _max: WorkspaceConfigurationMaxAggregateOutputType | null
}

export type WorkspaceConfigurationAvgAggregateOutputType = {
  smtpPort: number | null
}

export type WorkspaceConfigurationSumAggregateOutputType = {
  smtpPort: number | null
}

export type WorkspaceConfigurationMinAggregateOutputType = {
  id: string | null
  smtpPort: number | null
  smtpUsername: string | null
  smtpPassword: string | null
  createdAt: Date | null
  updatedAt: Date | null
  workspaceId: string | null
}

export type WorkspaceConfigurationMaxAggregateOutputType = {
  id: string | null
  smtpPort: number | null
  smtpUsername: string | null
  smtpPassword: string | null
  createdAt: Date | null
  updatedAt: Date | null
  workspaceId: string | null
}

export type WorkspaceConfigurationCountAggregateOutputType = {
  id: number
  smtpPort: number
  smtpUsername: number
  smtpPassword: number
  metadata: number
  createdAt: number
  updatedAt: number
  workspaceId: number
  _all: number
}


export type WorkspaceConfigurationAvgAggregateInputType = {
  smtpPort?: true
}

export type WorkspaceConfigurationSumAggregateInputType = {
  smtpPort?: true
}

export type WorkspaceConfigurationMinAggregateInputType = {
  id?: true
  smtpPort?: true
  smtpUsername?: true
  smtpPassword?: true
  createdAt?: true
  updatedAt?: true
  workspaceId?: true
}

export type WorkspaceConfigurationMaxAggregateInputType = {
  id?: true
  smtpPort?: true
  smtpUsername?: true
  smtpPassword?: true
  createdAt?: true
  updatedAt?: true
  workspaceId?: true
}

export type WorkspaceConfigurationCountAggregateInputType = {
  id?: true
  smtpPort?: true
  smtpUsername?: true
  smtpPassword?: true
  metadata?: true
  createdAt?: true
  updatedAt?: true
  workspaceId?: true
  _all?: true
}

export type WorkspaceConfigurationAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which WorkspaceConfiguration to aggregate.
   */
  where?: Prisma.WorkspaceConfigurationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkspaceConfigurations to fetch.
   */
  orderBy?: Prisma.WorkspaceConfigurationOrderByWithRelationInput | Prisma.WorkspaceConfigurationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.WorkspaceConfigurationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkspaceConfigurations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkspaceConfigurations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned WorkspaceConfigurations
  **/
  _count?: true | WorkspaceConfigurationCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: WorkspaceConfigurationAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: WorkspaceConfigurationSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: WorkspaceConfigurationMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: WorkspaceConfigurationMaxAggregateInputType
}

export type GetWorkspaceConfigurationAggregateType<T extends WorkspaceConfigurationAggregateArgs> = {
      [P in keyof T & keyof AggregateWorkspaceConfiguration]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateWorkspaceConfiguration[P]>
    : Prisma.GetScalarType<T[P], AggregateWorkspaceConfiguration[P]>
}




export type WorkspaceConfigurationGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.WorkspaceConfigurationWhereInput
  orderBy?: Prisma.WorkspaceConfigurationOrderByWithAggregationInput | Prisma.WorkspaceConfigurationOrderByWithAggregationInput[]
  by: Prisma.WorkspaceConfigurationScalarFieldEnum[] | Prisma.WorkspaceConfigurationScalarFieldEnum
  having?: Prisma.WorkspaceConfigurationScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: WorkspaceConfigurationCountAggregateInputType | true
  _avg?: WorkspaceConfigurationAvgAggregateInputType
  _sum?: WorkspaceConfigurationSumAggregateInputType
  _min?: WorkspaceConfigurationMinAggregateInputType
  _max?: WorkspaceConfigurationMaxAggregateInputType
}

export type WorkspaceConfigurationGroupByOutputType = {
  id: string
  smtpPort: number | null
  smtpUsername: string | null
  smtpPassword: string | null
  metadata: runtime.JsonValue
  createdAt: Date
  updatedAt: Date
  workspaceId: string
  _count: WorkspaceConfigurationCountAggregateOutputType | null
  _avg: WorkspaceConfigurationAvgAggregateOutputType | null
  _sum: WorkspaceConfigurationSumAggregateOutputType | null
  _min: WorkspaceConfigurationMinAggregateOutputType | null
  _max: WorkspaceConfigurationMaxAggregateOutputType | null
}

type GetWorkspaceConfigurationGroupByPayload<T extends WorkspaceConfigurationGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<WorkspaceConfigurationGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof WorkspaceConfigurationGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], WorkspaceConfigurationGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], WorkspaceConfigurationGroupByOutputType[P]>
      }
    >
  >



export type WorkspaceConfigurationWhereInput = {
  AND?: Prisma.WorkspaceConfigurationWhereInput | Prisma.WorkspaceConfigurationWhereInput[]
  OR?: Prisma.WorkspaceConfigurationWhereInput[]
  NOT?: Prisma.WorkspaceConfigurationWhereInput | Prisma.WorkspaceConfigurationWhereInput[]
  id?: Prisma.StringFilter<"WorkspaceConfiguration"> | string
  smtpPort?: Prisma.IntNullableFilter<"WorkspaceConfiguration"> | number | null
  smtpUsername?: Prisma.StringNullableFilter<"WorkspaceConfiguration"> | string | null
  smtpPassword?: Prisma.StringNullableFilter<"WorkspaceConfiguration"> | string | null
  metadata?: Prisma.JsonFilter<"WorkspaceConfiguration">
  createdAt?: Prisma.DateTimeFilter<"WorkspaceConfiguration"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"WorkspaceConfiguration"> | Date | string
  workspaceId?: Prisma.StringFilter<"WorkspaceConfiguration"> | string
  workspace?: Prisma.XOR<Prisma.WorkspaceScalarRelationFilter, Prisma.WorkspaceWhereInput>
}

export type WorkspaceConfigurationOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  smtpPort?: Prisma.SortOrderInput | Prisma.SortOrder
  smtpUsername?: Prisma.SortOrderInput | Prisma.SortOrder
  smtpPassword?: Prisma.SortOrderInput | Prisma.SortOrder
  metadata?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  workspaceId?: Prisma.SortOrder
  workspace?: Prisma.WorkspaceOrderByWithRelationInput
}

export type WorkspaceConfigurationWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  workspaceId?: string
  AND?: Prisma.WorkspaceConfigurationWhereInput | Prisma.WorkspaceConfigurationWhereInput[]
  OR?: Prisma.WorkspaceConfigurationWhereInput[]
  NOT?: Prisma.WorkspaceConfigurationWhereInput | Prisma.WorkspaceConfigurationWhereInput[]
  smtpPort?: Prisma.IntNullableFilter<"WorkspaceConfiguration"> | number | null
  smtpUsername?: Prisma.StringNullableFilter<"WorkspaceConfiguration"> | string | null
  smtpPassword?: Prisma.StringNullableFilter<"WorkspaceConfiguration"> | string | null
  metadata?: Prisma.JsonFilter<"WorkspaceConfiguration">
  createdAt?: Prisma.DateTimeFilter<"WorkspaceConfiguration"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"WorkspaceConfiguration"> | Date | string
  workspace?: Prisma.XOR<Prisma.WorkspaceScalarRelationFilter, Prisma.WorkspaceWhereInput>
}, "id" | "workspaceId">

export type WorkspaceConfigurationOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  smtpPort?: Prisma.SortOrderInput | Prisma.SortOrder
  smtpUsername?: Prisma.SortOrderInput | Prisma.SortOrder
  smtpPassword?: Prisma.SortOrderInput | Prisma.SortOrder
  metadata?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  workspaceId?: Prisma.SortOrder
  _count?: Prisma.WorkspaceConfigurationCountOrderByAggregateInput
  _avg?: Prisma.WorkspaceConfigurationAvgOrderByAggregateInput
  _max?: Prisma.WorkspaceConfigurationMaxOrderByAggregateInput
  _min?: Prisma.WorkspaceConfigurationMinOrderByAggregateInput
  _sum?: Prisma.WorkspaceConfigurationSumOrderByAggregateInput
}

export type WorkspaceConfigurationScalarWhereWithAggregatesInput = {
  AND?: Prisma.WorkspaceConfigurationScalarWhereWithAggregatesInput | Prisma.WorkspaceConfigurationScalarWhereWithAggregatesInput[]
  OR?: Prisma.WorkspaceConfigurationScalarWhereWithAggregatesInput[]
  NOT?: Prisma.WorkspaceConfigurationScalarWhereWithAggregatesInput | Prisma.WorkspaceConfigurationScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"WorkspaceConfiguration"> | string
  smtpPort?: Prisma.IntNullableWithAggregatesFilter<"WorkspaceConfiguration"> | number | null
  smtpUsername?: Prisma.StringNullableWithAggregatesFilter<"WorkspaceConfiguration"> | string | null
  smtpPassword?: Prisma.StringNullableWithAggregatesFilter<"WorkspaceConfiguration"> | string | null
  metadata?: Prisma.JsonWithAggregatesFilter<"WorkspaceConfiguration">
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"WorkspaceConfiguration"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"WorkspaceConfiguration"> | Date | string
  workspaceId?: Prisma.StringWithAggregatesFilter<"WorkspaceConfiguration"> | string
}

export type WorkspaceConfigurationCreateInput = {
  id?: string
  smtpPort?: number | null
  smtpUsername?: string | null
  smtpPassword?: string | null
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  workspace: Prisma.WorkspaceCreateNestedOneWithoutWorkspaceConfigurationInput
}

export type WorkspaceConfigurationUncheckedCreateInput = {
  id?: string
  smtpPort?: number | null
  smtpUsername?: string | null
  smtpPassword?: string | null
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  workspaceId: string
}

export type WorkspaceConfigurationUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  smtpPort?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  smtpUsername?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  smtpPassword?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workspace?: Prisma.WorkspaceUpdateOneRequiredWithoutWorkspaceConfigurationNestedInput
}

export type WorkspaceConfigurationUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  smtpPort?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  smtpUsername?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  smtpPassword?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workspaceId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type WorkspaceConfigurationCreateManyInput = {
  id?: string
  smtpPort?: number | null
  smtpUsername?: string | null
  smtpPassword?: string | null
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  workspaceId: string
}

export type WorkspaceConfigurationUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  smtpPort?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  smtpUsername?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  smtpPassword?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkspaceConfigurationUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  smtpPort?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  smtpUsername?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  smtpPassword?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workspaceId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type WorkspaceConfigurationListRelationFilter = {
  every?: Prisma.WorkspaceConfigurationWhereInput
  some?: Prisma.WorkspaceConfigurationWhereInput
  none?: Prisma.WorkspaceConfigurationWhereInput
}

export type WorkspaceConfigurationOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type WorkspaceConfigurationCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  smtpPort?: Prisma.SortOrder
  smtpUsername?: Prisma.SortOrder
  smtpPassword?: Prisma.SortOrder
  metadata?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  workspaceId?: Prisma.SortOrder
}

export type WorkspaceConfigurationAvgOrderByAggregateInput = {
  smtpPort?: Prisma.SortOrder
}

export type WorkspaceConfigurationMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  smtpPort?: Prisma.SortOrder
  smtpUsername?: Prisma.SortOrder
  smtpPassword?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  workspaceId?: Prisma.SortOrder
}

export type WorkspaceConfigurationMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  smtpPort?: Prisma.SortOrder
  smtpUsername?: Prisma.SortOrder
  smtpPassword?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  workspaceId?: Prisma.SortOrder
}

export type WorkspaceConfigurationSumOrderByAggregateInput = {
  smtpPort?: Prisma.SortOrder
}

export type WorkspaceConfigurationCreateNestedManyWithoutWorkspaceInput = {
  create?: Prisma.XOR<Prisma.WorkspaceConfigurationCreateWithoutWorkspaceInput, Prisma.WorkspaceConfigurationUncheckedCreateWithoutWorkspaceInput> | Prisma.WorkspaceConfigurationCreateWithoutWorkspaceInput[] | Prisma.WorkspaceConfigurationUncheckedCreateWithoutWorkspaceInput[]
  connectOrCreate?: Prisma.WorkspaceConfigurationCreateOrConnectWithoutWorkspaceInput | Prisma.WorkspaceConfigurationCreateOrConnectWithoutWorkspaceInput[]
  createMany?: Prisma.WorkspaceConfigurationCreateManyWorkspaceInputEnvelope
  connect?: Prisma.WorkspaceConfigurationWhereUniqueInput | Prisma.WorkspaceConfigurationWhereUniqueInput[]
}

export type WorkspaceConfigurationUncheckedCreateNestedManyWithoutWorkspaceInput = {
  create?: Prisma.XOR<Prisma.WorkspaceConfigurationCreateWithoutWorkspaceInput, Prisma.WorkspaceConfigurationUncheckedCreateWithoutWorkspaceInput> | Prisma.WorkspaceConfigurationCreateWithoutWorkspaceInput[] | Prisma.WorkspaceConfigurationUncheckedCreateWithoutWorkspaceInput[]
  connectOrCreate?: Prisma.WorkspaceConfigurationCreateOrConnectWithoutWorkspaceInput | Prisma.WorkspaceConfigurationCreateOrConnectWithoutWorkspaceInput[]
  createMany?: Prisma.WorkspaceConfigurationCreateManyWorkspaceInputEnvelope
  connect?: Prisma.WorkspaceConfigurationWhereUniqueInput | Prisma.WorkspaceConfigurationWhereUniqueInput[]
}

export type WorkspaceConfigurationUpdateManyWithoutWorkspaceNestedInput = {
  create?: Prisma.XOR<Prisma.WorkspaceConfigurationCreateWithoutWorkspaceInput, Prisma.WorkspaceConfigurationUncheckedCreateWithoutWorkspaceInput> | Prisma.WorkspaceConfigurationCreateWithoutWorkspaceInput[] | Prisma.WorkspaceConfigurationUncheckedCreateWithoutWorkspaceInput[]
  connectOrCreate?: Prisma.WorkspaceConfigurationCreateOrConnectWithoutWorkspaceInput | Prisma.WorkspaceConfigurationCreateOrConnectWithoutWorkspaceInput[]
  upsert?: Prisma.WorkspaceConfigurationUpsertWithWhereUniqueWithoutWorkspaceInput | Prisma.WorkspaceConfigurationUpsertWithWhereUniqueWithoutWorkspaceInput[]
  createMany?: Prisma.WorkspaceConfigurationCreateManyWorkspaceInputEnvelope
  set?: Prisma.WorkspaceConfigurationWhereUniqueInput | Prisma.WorkspaceConfigurationWhereUniqueInput[]
  disconnect?: Prisma.WorkspaceConfigurationWhereUniqueInput | Prisma.WorkspaceConfigurationWhereUniqueInput[]
  delete?: Prisma.WorkspaceConfigurationWhereUniqueInput | Prisma.WorkspaceConfigurationWhereUniqueInput[]
  connect?: Prisma.WorkspaceConfigurationWhereUniqueInput | Prisma.WorkspaceConfigurationWhereUniqueInput[]
  update?: Prisma.WorkspaceConfigurationUpdateWithWhereUniqueWithoutWorkspaceInput | Prisma.WorkspaceConfigurationUpdateWithWhereUniqueWithoutWorkspaceInput[]
  updateMany?: Prisma.WorkspaceConfigurationUpdateManyWithWhereWithoutWorkspaceInput | Prisma.WorkspaceConfigurationUpdateManyWithWhereWithoutWorkspaceInput[]
  deleteMany?: Prisma.WorkspaceConfigurationScalarWhereInput | Prisma.WorkspaceConfigurationScalarWhereInput[]
}

export type WorkspaceConfigurationUncheckedUpdateManyWithoutWorkspaceNestedInput = {
  create?: Prisma.XOR<Prisma.WorkspaceConfigurationCreateWithoutWorkspaceInput, Prisma.WorkspaceConfigurationUncheckedCreateWithoutWorkspaceInput> | Prisma.WorkspaceConfigurationCreateWithoutWorkspaceInput[] | Prisma.WorkspaceConfigurationUncheckedCreateWithoutWorkspaceInput[]
  connectOrCreate?: Prisma.WorkspaceConfigurationCreateOrConnectWithoutWorkspaceInput | Prisma.WorkspaceConfigurationCreateOrConnectWithoutWorkspaceInput[]
  upsert?: Prisma.WorkspaceConfigurationUpsertWithWhereUniqueWithoutWorkspaceInput | Prisma.WorkspaceConfigurationUpsertWithWhereUniqueWithoutWorkspaceInput[]
  createMany?: Prisma.WorkspaceConfigurationCreateManyWorkspaceInputEnvelope
  set?: Prisma.WorkspaceConfigurationWhereUniqueInput | Prisma.WorkspaceConfigurationWhereUniqueInput[]
  disconnect?: Prisma.WorkspaceConfigurationWhereUniqueInput | Prisma.WorkspaceConfigurationWhereUniqueInput[]
  delete?: Prisma.WorkspaceConfigurationWhereUniqueInput | Prisma.WorkspaceConfigurationWhereUniqueInput[]
  connect?: Prisma.WorkspaceConfigurationWhereUniqueInput | Prisma.WorkspaceConfigurationWhereUniqueInput[]
  update?: Prisma.WorkspaceConfigurationUpdateWithWhereUniqueWithoutWorkspaceInput | Prisma.WorkspaceConfigurationUpdateWithWhereUniqueWithoutWorkspaceInput[]
  updateMany?: Prisma.WorkspaceConfigurationUpdateManyWithWhereWithoutWorkspaceInput | Prisma.WorkspaceConfigurationUpdateManyWithWhereWithoutWorkspaceInput[]
  deleteMany?: Prisma.WorkspaceConfigurationScalarWhereInput | Prisma.WorkspaceConfigurationScalarWhereInput[]
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type WorkspaceConfigurationCreateWithoutWorkspaceInput = {
  id?: string
  smtpPort?: number | null
  smtpUsername?: string | null
  smtpPassword?: string | null
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type WorkspaceConfigurationUncheckedCreateWithoutWorkspaceInput = {
  id?: string
  smtpPort?: number | null
  smtpUsername?: string | null
  smtpPassword?: string | null
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type WorkspaceConfigurationCreateOrConnectWithoutWorkspaceInput = {
  where: Prisma.WorkspaceConfigurationWhereUniqueInput
  create: Prisma.XOR<Prisma.WorkspaceConfigurationCreateWithoutWorkspaceInput, Prisma.WorkspaceConfigurationUncheckedCreateWithoutWorkspaceInput>
}

export type WorkspaceConfigurationCreateManyWorkspaceInputEnvelope = {
  data: Prisma.WorkspaceConfigurationCreateManyWorkspaceInput | Prisma.WorkspaceConfigurationCreateManyWorkspaceInput[]
}

export type WorkspaceConfigurationUpsertWithWhereUniqueWithoutWorkspaceInput = {
  where: Prisma.WorkspaceConfigurationWhereUniqueInput
  update: Prisma.XOR<Prisma.WorkspaceConfigurationUpdateWithoutWorkspaceInput, Prisma.WorkspaceConfigurationUncheckedUpdateWithoutWorkspaceInput>
  create: Prisma.XOR<Prisma.WorkspaceConfigurationCreateWithoutWorkspaceInput, Prisma.WorkspaceConfigurationUncheckedCreateWithoutWorkspaceInput>
}

export type WorkspaceConfigurationUpdateWithWhereUniqueWithoutWorkspaceInput = {
  where: Prisma.WorkspaceConfigurationWhereUniqueInput
  data: Prisma.XOR<Prisma.WorkspaceConfigurationUpdateWithoutWorkspaceInput, Prisma.WorkspaceConfigurationUncheckedUpdateWithoutWorkspaceInput>
}

export type WorkspaceConfigurationUpdateManyWithWhereWithoutWorkspaceInput = {
  where: Prisma.WorkspaceConfigurationScalarWhereInput
  data: Prisma.XOR<Prisma.WorkspaceConfigurationUpdateManyMutationInput, Prisma.WorkspaceConfigurationUncheckedUpdateManyWithoutWorkspaceInput>
}

export type WorkspaceConfigurationScalarWhereInput = {
  AND?: Prisma.WorkspaceConfigurationScalarWhereInput | Prisma.WorkspaceConfigurationScalarWhereInput[]
  OR?: Prisma.WorkspaceConfigurationScalarWhereInput[]
  NOT?: Prisma.WorkspaceConfigurationScalarWhereInput | Prisma.WorkspaceConfigurationScalarWhereInput[]
  id?: Prisma.StringFilter<"WorkspaceConfiguration"> | string
  smtpPort?: Prisma.IntNullableFilter<"WorkspaceConfiguration"> | number | null
  smtpUsername?: Prisma.StringNullableFilter<"WorkspaceConfiguration"> | string | null
  smtpPassword?: Prisma.StringNullableFilter<"WorkspaceConfiguration"> | string | null
  metadata?: Prisma.JsonFilter<"WorkspaceConfiguration">
  createdAt?: Prisma.DateTimeFilter<"WorkspaceConfiguration"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"WorkspaceConfiguration"> | Date | string
  workspaceId?: Prisma.StringFilter<"WorkspaceConfiguration"> | string
}

export type WorkspaceConfigurationCreateManyWorkspaceInput = {
  id?: string
  smtpPort?: number | null
  smtpUsername?: string | null
  smtpPassword?: string | null
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type WorkspaceConfigurationUpdateWithoutWorkspaceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  smtpPort?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  smtpUsername?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  smtpPassword?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkspaceConfigurationUncheckedUpdateWithoutWorkspaceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  smtpPort?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  smtpUsername?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  smtpPassword?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkspaceConfigurationUncheckedUpdateManyWithoutWorkspaceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  smtpPort?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  smtpUsername?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  smtpPassword?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type WorkspaceConfigurationSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  smtpPort?: boolean
  smtpUsername?: boolean
  smtpPassword?: boolean
  metadata?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  workspaceId?: boolean
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
}, ExtArgs["result"]["workspaceConfiguration"]>

export type WorkspaceConfigurationSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  smtpPort?: boolean
  smtpUsername?: boolean
  smtpPassword?: boolean
  metadata?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  workspaceId?: boolean
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
}, ExtArgs["result"]["workspaceConfiguration"]>

export type WorkspaceConfigurationSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  smtpPort?: boolean
  smtpUsername?: boolean
  smtpPassword?: boolean
  metadata?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  workspaceId?: boolean
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
}, ExtArgs["result"]["workspaceConfiguration"]>

export type WorkspaceConfigurationSelectScalar = {
  id?: boolean
  smtpPort?: boolean
  smtpUsername?: boolean
  smtpPassword?: boolean
  metadata?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  workspaceId?: boolean
}

export type WorkspaceConfigurationOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "smtpPort" | "smtpUsername" | "smtpPassword" | "metadata" | "createdAt" | "updatedAt" | "workspaceId", ExtArgs["result"]["workspaceConfiguration"]>
export type WorkspaceConfigurationInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
}
export type WorkspaceConfigurationIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
}
export type WorkspaceConfigurationIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
}

export type $WorkspaceConfigurationPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "WorkspaceConfiguration"
  objects: {
    workspace: Prisma.$WorkspacePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    smtpPort: number | null
    smtpUsername: string | null
    smtpPassword: string | null
    metadata: runtime.JsonValue
    createdAt: Date
    updatedAt: Date
    workspaceId: string
  }, ExtArgs["result"]["workspaceConfiguration"]>
  composites: {}
}

export type WorkspaceConfigurationGetPayload<S extends boolean | null | undefined | WorkspaceConfigurationDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$WorkspaceConfigurationPayload, S>

export type WorkspaceConfigurationCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<WorkspaceConfigurationFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: WorkspaceConfigurationCountAggregateInputType | true
  }

export interface WorkspaceConfigurationDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['WorkspaceConfiguration'], meta: { name: 'WorkspaceConfiguration' } }
  /**
   * Find zero or one WorkspaceConfiguration that matches the filter.
   * @param {WorkspaceConfigurationFindUniqueArgs} args - Arguments to find a WorkspaceConfiguration
   * @example
   * // Get one WorkspaceConfiguration
   * const workspaceConfiguration = await prisma.workspaceConfiguration.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends WorkspaceConfigurationFindUniqueArgs>(args: Prisma.SelectSubset<T, WorkspaceConfigurationFindUniqueArgs<ExtArgs>>): Prisma.Prisma__WorkspaceConfigurationClient<runtime.Types.Result.GetResult<Prisma.$WorkspaceConfigurationPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one WorkspaceConfiguration that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {WorkspaceConfigurationFindUniqueOrThrowArgs} args - Arguments to find a WorkspaceConfiguration
   * @example
   * // Get one WorkspaceConfiguration
   * const workspaceConfiguration = await prisma.workspaceConfiguration.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends WorkspaceConfigurationFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, WorkspaceConfigurationFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__WorkspaceConfigurationClient<runtime.Types.Result.GetResult<Prisma.$WorkspaceConfigurationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first WorkspaceConfiguration that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkspaceConfigurationFindFirstArgs} args - Arguments to find a WorkspaceConfiguration
   * @example
   * // Get one WorkspaceConfiguration
   * const workspaceConfiguration = await prisma.workspaceConfiguration.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends WorkspaceConfigurationFindFirstArgs>(args?: Prisma.SelectSubset<T, WorkspaceConfigurationFindFirstArgs<ExtArgs>>): Prisma.Prisma__WorkspaceConfigurationClient<runtime.Types.Result.GetResult<Prisma.$WorkspaceConfigurationPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first WorkspaceConfiguration that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkspaceConfigurationFindFirstOrThrowArgs} args - Arguments to find a WorkspaceConfiguration
   * @example
   * // Get one WorkspaceConfiguration
   * const workspaceConfiguration = await prisma.workspaceConfiguration.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends WorkspaceConfigurationFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, WorkspaceConfigurationFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__WorkspaceConfigurationClient<runtime.Types.Result.GetResult<Prisma.$WorkspaceConfigurationPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more WorkspaceConfigurations that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkspaceConfigurationFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all WorkspaceConfigurations
   * const workspaceConfigurations = await prisma.workspaceConfiguration.findMany()
   * 
   * // Get first 10 WorkspaceConfigurations
   * const workspaceConfigurations = await prisma.workspaceConfiguration.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const workspaceConfigurationWithIdOnly = await prisma.workspaceConfiguration.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends WorkspaceConfigurationFindManyArgs>(args?: Prisma.SelectSubset<T, WorkspaceConfigurationFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkspaceConfigurationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a WorkspaceConfiguration.
   * @param {WorkspaceConfigurationCreateArgs} args - Arguments to create a WorkspaceConfiguration.
   * @example
   * // Create one WorkspaceConfiguration
   * const WorkspaceConfiguration = await prisma.workspaceConfiguration.create({
   *   data: {
   *     // ... data to create a WorkspaceConfiguration
   *   }
   * })
   * 
   */
  create<T extends WorkspaceConfigurationCreateArgs>(args: Prisma.SelectSubset<T, WorkspaceConfigurationCreateArgs<ExtArgs>>): Prisma.Prisma__WorkspaceConfigurationClient<runtime.Types.Result.GetResult<Prisma.$WorkspaceConfigurationPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many WorkspaceConfigurations.
   * @param {WorkspaceConfigurationCreateManyArgs} args - Arguments to create many WorkspaceConfigurations.
   * @example
   * // Create many WorkspaceConfigurations
   * const workspaceConfiguration = await prisma.workspaceConfiguration.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends WorkspaceConfigurationCreateManyArgs>(args?: Prisma.SelectSubset<T, WorkspaceConfigurationCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many WorkspaceConfigurations and returns the data saved in the database.
   * @param {WorkspaceConfigurationCreateManyAndReturnArgs} args - Arguments to create many WorkspaceConfigurations.
   * @example
   * // Create many WorkspaceConfigurations
   * const workspaceConfiguration = await prisma.workspaceConfiguration.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many WorkspaceConfigurations and only return the `id`
   * const workspaceConfigurationWithIdOnly = await prisma.workspaceConfiguration.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends WorkspaceConfigurationCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, WorkspaceConfigurationCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkspaceConfigurationPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a WorkspaceConfiguration.
   * @param {WorkspaceConfigurationDeleteArgs} args - Arguments to delete one WorkspaceConfiguration.
   * @example
   * // Delete one WorkspaceConfiguration
   * const WorkspaceConfiguration = await prisma.workspaceConfiguration.delete({
   *   where: {
   *     // ... filter to delete one WorkspaceConfiguration
   *   }
   * })
   * 
   */
  delete<T extends WorkspaceConfigurationDeleteArgs>(args: Prisma.SelectSubset<T, WorkspaceConfigurationDeleteArgs<ExtArgs>>): Prisma.Prisma__WorkspaceConfigurationClient<runtime.Types.Result.GetResult<Prisma.$WorkspaceConfigurationPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one WorkspaceConfiguration.
   * @param {WorkspaceConfigurationUpdateArgs} args - Arguments to update one WorkspaceConfiguration.
   * @example
   * // Update one WorkspaceConfiguration
   * const workspaceConfiguration = await prisma.workspaceConfiguration.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends WorkspaceConfigurationUpdateArgs>(args: Prisma.SelectSubset<T, WorkspaceConfigurationUpdateArgs<ExtArgs>>): Prisma.Prisma__WorkspaceConfigurationClient<runtime.Types.Result.GetResult<Prisma.$WorkspaceConfigurationPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more WorkspaceConfigurations.
   * @param {WorkspaceConfigurationDeleteManyArgs} args - Arguments to filter WorkspaceConfigurations to delete.
   * @example
   * // Delete a few WorkspaceConfigurations
   * const { count } = await prisma.workspaceConfiguration.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends WorkspaceConfigurationDeleteManyArgs>(args?: Prisma.SelectSubset<T, WorkspaceConfigurationDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WorkspaceConfigurations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkspaceConfigurationUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many WorkspaceConfigurations
   * const workspaceConfiguration = await prisma.workspaceConfiguration.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends WorkspaceConfigurationUpdateManyArgs>(args: Prisma.SelectSubset<T, WorkspaceConfigurationUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WorkspaceConfigurations and returns the data updated in the database.
   * @param {WorkspaceConfigurationUpdateManyAndReturnArgs} args - Arguments to update many WorkspaceConfigurations.
   * @example
   * // Update many WorkspaceConfigurations
   * const workspaceConfiguration = await prisma.workspaceConfiguration.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more WorkspaceConfigurations and only return the `id`
   * const workspaceConfigurationWithIdOnly = await prisma.workspaceConfiguration.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends WorkspaceConfigurationUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, WorkspaceConfigurationUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkspaceConfigurationPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one WorkspaceConfiguration.
   * @param {WorkspaceConfigurationUpsertArgs} args - Arguments to update or create a WorkspaceConfiguration.
   * @example
   * // Update or create a WorkspaceConfiguration
   * const workspaceConfiguration = await prisma.workspaceConfiguration.upsert({
   *   create: {
   *     // ... data to create a WorkspaceConfiguration
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the WorkspaceConfiguration we want to update
   *   }
   * })
   */
  upsert<T extends WorkspaceConfigurationUpsertArgs>(args: Prisma.SelectSubset<T, WorkspaceConfigurationUpsertArgs<ExtArgs>>): Prisma.Prisma__WorkspaceConfigurationClient<runtime.Types.Result.GetResult<Prisma.$WorkspaceConfigurationPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of WorkspaceConfigurations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkspaceConfigurationCountArgs} args - Arguments to filter WorkspaceConfigurations to count.
   * @example
   * // Count the number of WorkspaceConfigurations
   * const count = await prisma.workspaceConfiguration.count({
   *   where: {
   *     // ... the filter for the WorkspaceConfigurations we want to count
   *   }
   * })
  **/
  count<T extends WorkspaceConfigurationCountArgs>(
    args?: Prisma.Subset<T, WorkspaceConfigurationCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], WorkspaceConfigurationCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a WorkspaceConfiguration.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkspaceConfigurationAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends WorkspaceConfigurationAggregateArgs>(args: Prisma.Subset<T, WorkspaceConfigurationAggregateArgs>): Prisma.PrismaPromise<GetWorkspaceConfigurationAggregateType<T>>

  /**
   * Group by WorkspaceConfiguration.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkspaceConfigurationGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends WorkspaceConfigurationGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: WorkspaceConfigurationGroupByArgs['orderBy'] }
      : { orderBy?: WorkspaceConfigurationGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, WorkspaceConfigurationGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetWorkspaceConfigurationGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the WorkspaceConfiguration model
 */
readonly fields: WorkspaceConfigurationFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for WorkspaceConfiguration.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__WorkspaceConfigurationClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  workspace<T extends Prisma.WorkspaceDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.WorkspaceDefaultArgs<ExtArgs>>): Prisma.Prisma__WorkspaceClient<runtime.Types.Result.GetResult<Prisma.$WorkspacePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the WorkspaceConfiguration model
 */
export interface WorkspaceConfigurationFieldRefs {
  readonly id: Prisma.FieldRef<"WorkspaceConfiguration", 'String'>
  readonly smtpPort: Prisma.FieldRef<"WorkspaceConfiguration", 'Int'>
  readonly smtpUsername: Prisma.FieldRef<"WorkspaceConfiguration", 'String'>
  readonly smtpPassword: Prisma.FieldRef<"WorkspaceConfiguration", 'String'>
  readonly metadata: Prisma.FieldRef<"WorkspaceConfiguration", 'Json'>
  readonly createdAt: Prisma.FieldRef<"WorkspaceConfiguration", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"WorkspaceConfiguration", 'DateTime'>
  readonly workspaceId: Prisma.FieldRef<"WorkspaceConfiguration", 'String'>
}
    

// Custom InputTypes
/**
 * WorkspaceConfiguration findUnique
 */
export type WorkspaceConfigurationFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkspaceConfiguration
   */
  select?: Prisma.WorkspaceConfigurationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkspaceConfiguration
   */
  omit?: Prisma.WorkspaceConfigurationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkspaceConfigurationInclude<ExtArgs> | null
  /**
   * Filter, which WorkspaceConfiguration to fetch.
   */
  where: Prisma.WorkspaceConfigurationWhereUniqueInput
}

/**
 * WorkspaceConfiguration findUniqueOrThrow
 */
export type WorkspaceConfigurationFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkspaceConfiguration
   */
  select?: Prisma.WorkspaceConfigurationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkspaceConfiguration
   */
  omit?: Prisma.WorkspaceConfigurationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkspaceConfigurationInclude<ExtArgs> | null
  /**
   * Filter, which WorkspaceConfiguration to fetch.
   */
  where: Prisma.WorkspaceConfigurationWhereUniqueInput
}

/**
 * WorkspaceConfiguration findFirst
 */
export type WorkspaceConfigurationFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkspaceConfiguration
   */
  select?: Prisma.WorkspaceConfigurationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkspaceConfiguration
   */
  omit?: Prisma.WorkspaceConfigurationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkspaceConfigurationInclude<ExtArgs> | null
  /**
   * Filter, which WorkspaceConfiguration to fetch.
   */
  where?: Prisma.WorkspaceConfigurationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkspaceConfigurations to fetch.
   */
  orderBy?: Prisma.WorkspaceConfigurationOrderByWithRelationInput | Prisma.WorkspaceConfigurationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for WorkspaceConfigurations.
   */
  cursor?: Prisma.WorkspaceConfigurationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkspaceConfigurations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkspaceConfigurations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WorkspaceConfigurations.
   */
  distinct?: Prisma.WorkspaceConfigurationScalarFieldEnum | Prisma.WorkspaceConfigurationScalarFieldEnum[]
}

/**
 * WorkspaceConfiguration findFirstOrThrow
 */
export type WorkspaceConfigurationFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkspaceConfiguration
   */
  select?: Prisma.WorkspaceConfigurationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkspaceConfiguration
   */
  omit?: Prisma.WorkspaceConfigurationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkspaceConfigurationInclude<ExtArgs> | null
  /**
   * Filter, which WorkspaceConfiguration to fetch.
   */
  where?: Prisma.WorkspaceConfigurationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkspaceConfigurations to fetch.
   */
  orderBy?: Prisma.WorkspaceConfigurationOrderByWithRelationInput | Prisma.WorkspaceConfigurationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for WorkspaceConfigurations.
   */
  cursor?: Prisma.WorkspaceConfigurationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkspaceConfigurations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkspaceConfigurations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WorkspaceConfigurations.
   */
  distinct?: Prisma.WorkspaceConfigurationScalarFieldEnum | Prisma.WorkspaceConfigurationScalarFieldEnum[]
}

/**
 * WorkspaceConfiguration findMany
 */
export type WorkspaceConfigurationFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkspaceConfiguration
   */
  select?: Prisma.WorkspaceConfigurationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkspaceConfiguration
   */
  omit?: Prisma.WorkspaceConfigurationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkspaceConfigurationInclude<ExtArgs> | null
  /**
   * Filter, which WorkspaceConfigurations to fetch.
   */
  where?: Prisma.WorkspaceConfigurationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkspaceConfigurations to fetch.
   */
  orderBy?: Prisma.WorkspaceConfigurationOrderByWithRelationInput | Prisma.WorkspaceConfigurationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing WorkspaceConfigurations.
   */
  cursor?: Prisma.WorkspaceConfigurationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkspaceConfigurations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkspaceConfigurations.
   */
  skip?: number
  distinct?: Prisma.WorkspaceConfigurationScalarFieldEnum | Prisma.WorkspaceConfigurationScalarFieldEnum[]
}

/**
 * WorkspaceConfiguration create
 */
export type WorkspaceConfigurationCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkspaceConfiguration
   */
  select?: Prisma.WorkspaceConfigurationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkspaceConfiguration
   */
  omit?: Prisma.WorkspaceConfigurationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkspaceConfigurationInclude<ExtArgs> | null
  /**
   * The data needed to create a WorkspaceConfiguration.
   */
  data: Prisma.XOR<Prisma.WorkspaceConfigurationCreateInput, Prisma.WorkspaceConfigurationUncheckedCreateInput>
}

/**
 * WorkspaceConfiguration createMany
 */
export type WorkspaceConfigurationCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many WorkspaceConfigurations.
   */
  data: Prisma.WorkspaceConfigurationCreateManyInput | Prisma.WorkspaceConfigurationCreateManyInput[]
}

/**
 * WorkspaceConfiguration createManyAndReturn
 */
export type WorkspaceConfigurationCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkspaceConfiguration
   */
  select?: Prisma.WorkspaceConfigurationSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the WorkspaceConfiguration
   */
  omit?: Prisma.WorkspaceConfigurationOmit<ExtArgs> | null
  /**
   * The data used to create many WorkspaceConfigurations.
   */
  data: Prisma.WorkspaceConfigurationCreateManyInput | Prisma.WorkspaceConfigurationCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkspaceConfigurationIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * WorkspaceConfiguration update
 */
export type WorkspaceConfigurationUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkspaceConfiguration
   */
  select?: Prisma.WorkspaceConfigurationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkspaceConfiguration
   */
  omit?: Prisma.WorkspaceConfigurationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkspaceConfigurationInclude<ExtArgs> | null
  /**
   * The data needed to update a WorkspaceConfiguration.
   */
  data: Prisma.XOR<Prisma.WorkspaceConfigurationUpdateInput, Prisma.WorkspaceConfigurationUncheckedUpdateInput>
  /**
   * Choose, which WorkspaceConfiguration to update.
   */
  where: Prisma.WorkspaceConfigurationWhereUniqueInput
}

/**
 * WorkspaceConfiguration updateMany
 */
export type WorkspaceConfigurationUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update WorkspaceConfigurations.
   */
  data: Prisma.XOR<Prisma.WorkspaceConfigurationUpdateManyMutationInput, Prisma.WorkspaceConfigurationUncheckedUpdateManyInput>
  /**
   * Filter which WorkspaceConfigurations to update
   */
  where?: Prisma.WorkspaceConfigurationWhereInput
  /**
   * Limit how many WorkspaceConfigurations to update.
   */
  limit?: number
}

/**
 * WorkspaceConfiguration updateManyAndReturn
 */
export type WorkspaceConfigurationUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkspaceConfiguration
   */
  select?: Prisma.WorkspaceConfigurationSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the WorkspaceConfiguration
   */
  omit?: Prisma.WorkspaceConfigurationOmit<ExtArgs> | null
  /**
   * The data used to update WorkspaceConfigurations.
   */
  data: Prisma.XOR<Prisma.WorkspaceConfigurationUpdateManyMutationInput, Prisma.WorkspaceConfigurationUncheckedUpdateManyInput>
  /**
   * Filter which WorkspaceConfigurations to update
   */
  where?: Prisma.WorkspaceConfigurationWhereInput
  /**
   * Limit how many WorkspaceConfigurations to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkspaceConfigurationIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * WorkspaceConfiguration upsert
 */
export type WorkspaceConfigurationUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkspaceConfiguration
   */
  select?: Prisma.WorkspaceConfigurationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkspaceConfiguration
   */
  omit?: Prisma.WorkspaceConfigurationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkspaceConfigurationInclude<ExtArgs> | null
  /**
   * The filter to search for the WorkspaceConfiguration to update in case it exists.
   */
  where: Prisma.WorkspaceConfigurationWhereUniqueInput
  /**
   * In case the WorkspaceConfiguration found by the `where` argument doesn't exist, create a new WorkspaceConfiguration with this data.
   */
  create: Prisma.XOR<Prisma.WorkspaceConfigurationCreateInput, Prisma.WorkspaceConfigurationUncheckedCreateInput>
  /**
   * In case the WorkspaceConfiguration was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.WorkspaceConfigurationUpdateInput, Prisma.WorkspaceConfigurationUncheckedUpdateInput>
}

/**
 * WorkspaceConfiguration delete
 */
export type WorkspaceConfigurationDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkspaceConfiguration
   */
  select?: Prisma.WorkspaceConfigurationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkspaceConfiguration
   */
  omit?: Prisma.WorkspaceConfigurationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkspaceConfigurationInclude<ExtArgs> | null
  /**
   * Filter which WorkspaceConfiguration to delete.
   */
  where: Prisma.WorkspaceConfigurationWhereUniqueInput
}

/**
 * WorkspaceConfiguration deleteMany
 */
export type WorkspaceConfigurationDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which WorkspaceConfigurations to delete
   */
  where?: Prisma.WorkspaceConfigurationWhereInput
  /**
   * Limit how many WorkspaceConfigurations to delete.
   */
  limit?: number
}

/**
 * WorkspaceConfiguration without action
 */
export type WorkspaceConfigurationDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkspaceConfiguration
   */
  select?: Prisma.WorkspaceConfigurationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkspaceConfiguration
   */
  omit?: Prisma.WorkspaceConfigurationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkspaceConfigurationInclude<ExtArgs> | null
}
