import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, join } from 'node:path';
import type {
  YasumuThemeConfig,
  YasumuThemeVariables,
} from '../apps/yasumu/src/lib/types/theme.ts';

const isCompact = process.argv.includes('--compact');
const themesDir = join(import.meta.dirname, 'presets');
const outputDir = join(import.meta.dirname, 'output');
const compactOutputFile = join(
  import.meta.dirname,
  '../apps/yasumu/src/lib/constants/builtin-themes.ts',
);

function parseThemeName(filename: string): string {
  const parts = basename(filename, '.css').split('.');
  if (parts.length > 1) {
    return parts
      .slice(1)
      .join(' ')
      .replace(/-/g, ' ')
      .replace(/\b\w/g, (c) => c.toUpperCase());
  }
  return parts[0].replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
}

function parseCssVariables(cssBlock: string): YasumuThemeVariables {
  const variables: YasumuThemeVariables = {};
  const lines = cssBlock.split('\n');

  let currentVar = '';
  let currentValue = '';
  let isMultiLine = false;

  for (const line of lines) {
    const trimmed = line.trim();

    if (isMultiLine) {
      currentValue += ' ' + trimmed.replace(/;$/, '');
      if (trimmed.endsWith(';')) {
        isMultiLine = false;
        const key = currentVar.replace(/^--/, '') as keyof YasumuThemeVariables;
        variables[key] = currentValue.trim();
        currentVar = '';
        currentValue = '';
      }
      continue;
    }

    const matchWithValue = trimmed.match(/^(--[\w-]+):\s*(.+)$/);
    const matchVarOnly = trimmed.match(/^(--[\w-]+):$/);

    if (matchWithValue) {
      const [, varName, value] = matchWithValue;
      if (value.endsWith(';')) {
        const key = varName.replace(/^--/, '') as keyof YasumuThemeVariables;
        variables[key] = value.slice(0, -1).trim();
      } else {
        currentVar = varName;
        currentValue = value;
        isMultiLine = true;
      }
    } else if (matchVarOnly) {
      currentVar = matchVarOnly[1];
      currentValue = '';
      isMultiLine = true;
    }
  }

  return variables;
}

function parseCssFile(content: string): {
  light: YasumuThemeVariables;
  dark: YasumuThemeVariables;
} {
  const rootMatch = content.match(/:root\s*\{([^}]+(?:\{[^}]*\}[^}]*)*)\}/s);
  const darkMatch = content.match(/\.dark\s*\{([^}]+(?:\{[^}]*\}[^}]*)*)\}/s);

  const light = rootMatch ? parseCssVariables(rootMatch[1]) : {};
  const dark = darkMatch ? parseCssVariables(darkMatch[1]) : {};

  return { light, dark };
}

const themeFiles = readdirSync(themesDir).filter((f) => f.endsWith('.css'));
const outputThemes: YasumuThemeConfig[] = [];

mkdirSync(outputDir, { recursive: true });

for (const themeFile of themeFiles) {
  const filePath = join(themesDir, themeFile);
  const content = readFileSync(filePath, 'utf-8');
  const themeId = basename(themeFile, '.css');
  const themeName = parseThemeName(themeFile);

  const { light, dark } = parseCssFile(content);

  const lightTheme: YasumuThemeConfig = {
    id: `${themeId}-light`,
    name: themeName,
    type: 'light',
    variables: light,
  };

  const darkTheme: YasumuThemeConfig = {
    id: `${themeId}-dark`,
    name: themeName,
    type: 'dark',
    variables: dark,
  };

  outputThemes.push(lightTheme, darkTheme);

  if (!isCompact) {
    writeFileSync(
      join(outputDir, `${themeId}-light.json`),
      JSON.stringify(lightTheme, null, 2),
    );
    writeFileSync(
      join(outputDir, `${themeId}-dark.json`),
      JSON.stringify(darkTheme, null, 2),
    );
    console.log(`Generated: ${themeId}-light.json, ${themeId}-dark.json`);
  }
}

if (isCompact) {
  if (compactOutputFile.endsWith('.ts')) {
    const BANNER = `/*
 * This file is auto-generated by the theme converter in $ROOT/themes/converter.ts
 * Do not edit this file manually.
 */
`;
    writeFileSync(
      compactOutputFile,
      `/* eslint-disable */\n// @ts-nocheck\n\n\n${BANNER}\n\nimport type { YasumuThemeConfig } from '@/lib/types/theme';\n\nexport const BUILTIN_THEMES: YasumuThemeConfig[] = ${JSON.stringify(outputThemes)};\n`,
    );
    console.log(
      `Generated: ${compactOutputFile} (${outputThemes.length} themes)`,
    );
  } else {
    writeFileSync(
      join(outputDir, 'themes.json'),
      JSON.stringify(outputThemes, null, 2),
    );
    console.log(`Generated: themes.json (${outputThemes.length} themes)`);
  }
}

console.log(
  `\nDone! Processed ${themeFiles.length} CSS files into ${outputThemes.length} theme configs.`,
);
