name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint & Type Check
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11.11.0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 2.9.2

      - name: Install dependencies
        run: pnpm install --frozen-lockfile && pnpm --filter=tanxium deno install

      # - name: Lint
      #   run: pnpm turbo run lint

      - name: Type check
        run: pnpm build:app
        env:
          TURBO_TEAM: ${{ secrets.YASUMU_TURBO_TEAM }}
          TURBO_TOKEN: ${{ secrets.YASUMU_TURBO_TOKEN }}

  cargo:
    name: Cargo Check
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf xdg-utils

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./apps/yasumu/src-tauri -> target"
          cache-on-failure: true
          shared-key: yasumu-check

      - name: Cargo check
        run: cargo check
        working-directory: ./apps/yasumu/src-tauri
